Anton version
sergey-berezin/441_sherbakov pull request #1
Opened 2022-09-28 19:02 UTC by SheDDW121

2022-10-03 10:11 UTC, sergey-berezin requested changes

2022-10-03 10:11 UTC, sergey-berezin commented on library/Emotions.cs
> +        public List<CancellationTokenSource> cts = new List<CancellationTokenSource>();
Обычно компонент не управляет `CancellationTokenSource`, а получает `CancellationToken` извне.

2022-10-03 10:11 UTC, sergey-berezin commented on library/Emotions.cs
> +                    using var modelStream = typeof(Emotions).Assembly.GetManifestResourceStream("emotion.onnx");
Для каждого вызова загружается новая нейронная сеть

2022-10-03 10:11 UTC, sergey-berezin commented on library/Emotions.cs
> +                myReporter.ReportError(ex.Message);
IErrorReporter здесь является излишним усложнением

2022-10-03 19:26 UTC, SheDDW121 commented on library/Emotions.cs
> +        public List<CancellationTokenSource> cts = new List<CancellationTokenSource>();
Здравствуйте, все исправил (3 ошибки), посмотрите, пожалуйста

2022-10-10 10:07 UTC, sergey-berezin commented on Lab1/library/Emotions.cs
> +        public async Task<IEnumerable <(string, double)>> GetMostLikelyEmotionsAsync (byte[] img, CancellationTokenSource? cts = null, string? taskName = null) {
Правильнее использовать `CancellationToken` в клиентах

2022-10-10 10:07 UTC, sergey-berezin approved these changes

2022-10-10 10:07 UTC, merged